---

- hosts: localhost
  vars:
    name: username
    time: 00.00
    threadts: 0
    
  tasks:
  
  - name: message
    set_fact:
      slack_message: >-
       {
          "channel":"C02CF7R2KPV",
          "thread_ts": "{{threadts}}",
          "text":"<@{{ name }}> toplantı için saat {{ time }}'i seçti."
       }
       
  - name: send message
    uri:
      url: "https://slack.com/api/chat.postMessage"
      headers:
        Content-Type: "application/json; charset=utf-8"
        Authorization: "Bearer xoxb-2401101278246-2423055508898-o0AYLSyzHNs0jjrHsAPEMUpe"
      body: "{{ slack_message }}"
      method: POST
      body_format: json
      return_content: yes
    register: slack_response
    delegate_to: localhost
    
  - name: write slack response
    debug:
      msg: "{{slack_response}}"
